version: "3.7"
volumes:
  cl-judge-pics:

services:
  cl-python:
    container_name: cl-python
    image: freelawproject/freelawproject/courtlistener:latest-web-prod
    depends_on:
      - cl-judge-pics
      - cl-selenium
    expose:
      - 8000
    volumes:
      - ${BULK_DIR:-/sata/}:/storage/
      - cl-judge-pics:${PYTHON_PACKAGES}/judge_pics
    environment:
      # Make it easy to connect to selenium. Juriscraper will pick up this var.
      - WEBDRIVER_CONN=http://cl-selenium:4444/wd/hub
    logging:
      driver: journald
    extra_hosts:
      - "localhost:192.168.0.122"
    restart: on-failure

  cl-scrape-rss:
    container_name: cl-scrape-rss
    image: freelawproject/courtlistener:latest-rss-scraper
    volumes:
      - ${BULK_DIR:-/sata/}:/storage/
      - cl-judge-pics:${PYTHON_PACKAGES}/judge_pics
    logging:
      driver: journald
    user: www-data
    extra_hosts:
      - "localhost:192.168.0.122"
    restart: on-failure

  # Before renaming this service, see: freelawproject/courtlistener#1433
  cl-nginx:
    container_name: cl-nginx
    image: freelawproject/nginx:latest
    depends_on:
      - cl-python
    volumes:
      - cl-judge-pics:${PYTHON_PACKAGES}/judge_pics
      - ${CERT_HOME:-/etc/letsencrypt}:/etc/letsencrypt:ro
      - ${BULK_DIR:-/sata/}:/storage/
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: journald
    extra_hosts:
      - "localhost:192.168.0.122"
    restart: on-failure

  cl-selenium:
    container_name: cl-selenium-scraper
    image: selenium/standalone-firefox-debug
    ports:
      - 4444:4444  # Selenium
    volumes:
      - ${CL_SHM_DIR:-/dev/shm}:/dev/shm
    logging:
      driver: journald
    extra_hosts:
      - "localhost:192.168.0.122"
    restart: on-failure

  cl-judge-pics:
    image: freelawproject/judge-pics:latest
    container_name: "cl-judge-pics"
    volumes:
      - cl-judge-pics:${PYTHON_PACKAGES}/judge_pics
    deploy:
      restart_policy:
        condition: none

  cl-doctor:
    image: freelawproject/doctor:latest
    container_name: "cl-doctor"
    networks:
      - cl_net_overlay
    logging:
      driver: journald
